version: '3'
services:

  #Laravel Service
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: survey-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - survey

  #Nginx Service
  nginx:
    image: nginx:1.17-alpine
    container_name: survey-nginx
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./:/var/www
      - ./docker-compose:/etc/nginx/conf.d
    networks:
      - survey

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db_survey
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: layanan_survey_pelanggan
      MYSQL_ROOT_PASSWORD: Rahasia123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - survey

networks:
  survey:
    driver: bridge
volumes:
  dbdata:
    driver: local