version: '3'
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: survey-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - survey
  nginx:
    image: nginx:1.17-alpine
    container_name: survey-nginx
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./:/var/www
      - ./docker-compose:/etc/nginx/conf.d
    networks:
      - survey

networks:
  survey:
    driver: bridge